server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  profiles:
    active: native
  datasource:
    url: jdbc:postgresql://localhost:5432/nome_do_banco
    username: seu_usuario
    password: sua_senha
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  application-version: 1.0
